sonar.projectKey=aceest-fitness-app
sonar.projectName=ACEest Fitness App
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=test_*.py
sonar.exclusions=venv/**,.venv/**,__pycache__/**,.pytest_cache/**,k8s/**,aceest_fitness.db
sonar.python.coverage.reportPaths=coverage.xml
